export const PARKING_FETCH_REQUESTED = 'PARKING_FETCH_REQUESTED';
export const PARKING_FETCH_SUCCEEDED = 'PARKING_FETCH_SUCCEEDED';
export const PARKING_FETCH_FAILED = 'PARKING_FETCH_FAILED';

export const SESSIONS_FETCH_REQUESTED = 'SESSIONS_FETCH_REQUESTED';
export const SESSIONS_FETCH_SUCCEEDED = 'SESSIONS_FETCH_SUCCEEDED';
export const SESSIONS_FETCH_FAILED = 'SESSIONS_FETCH_FAILED';
